<a href="https://colab.research.google.com/github/welovecherry/colab/blob/main/Numpy_study_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
# 넘파이는 한줄로 모든 요소에 10 더하기 가능

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_added = arr + 10
# print(arr_added)


# 넘파이는 자동 메모리 관리해줌.
# 씨언어는 2차원배열 만들 때 [3][3]처럼 크기를 명확히 해야하지만
# 넘파이는 이런걸 쓸 필요 없다.

matrix = np.array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix * 100)
print(matrix.T)
print(matrix) # original

# 넘파이: average, std(표준편차), sum 바로 사용가능
# print(np.mean(arr))
# print(np.std(arr))
# print(np.sum(arr))


[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 차원을 표현할 때 [] 를 쓴다. 만일 2차원 배열을 만들면 []를 2번 씀
# 2차원 배열 (행렬)
matrix = np.array([
    [1, 2, 3],    # 첫 번째 행
    [4, 5, 6],    # 두 번째 행
    [7, 8, 9]     # 세 번째 행
])
# 각 []는 차원을 나타냄
# 1번 []는 전체 행렬
# 2번 []는 각 행

# 3차원 배열 (텐서)
tensor = np.array([
    [[1, 2], [3, 4]],    # 첫 번째 2D 배열
    [[5, 6], [7, 8]]     # 두 번째 2D 배열
])
# 1번 []는 전체 텐서
# 2번 []는 각 2D 배열
# 3번 []는 각 2D 배열 내 행

In [58]:
matrix = np.array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# print(matrix[1, 2]) # 1행 2열 (idex starts from 0)

# 넘파이는 슬라이싱 사용 가능 (슬라이싱이 복사가 아니라 참조되므로 원본 배열이 변경될 수 있다.)
# print(matrix[:2])


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# print(arr[2:5])
# print(arr[:4])
print(arr[5:])
# print(arr[:])

# print(arr[1:8:2])  # 인덱스 1부터 7까지 2칸씩 건너뛰기
# print(arr[::-1])   # 배열을 거꾸로 뒤집기
# print(arr[::3])    # 처음부터 끝까지 3칸씩 건너뛰기

# 2차원 배열에서도 넘파이 슬라이싱 사용 가능
arr2d = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

# 넘파이는 조건을 활용한 슬라이싱(필터링) 가능
# print(arr[arr > 4])


# (슬라이싱이 복사가 아니라 참조되므로 원본 배열이 변경될 수 있다.)
arr = np.array([1, 2, 3, 4])
sub_arr = arr[1:3]  # 부분 배열 (view)

sub_arr[0] = 99  # 부분 배열 수정
# print(arr)  # 원본 배열도 변경됨!


sub_arr_cpy = arr[1:3].copy()
sub_arr_cpy[0] = 10000
# print(arr)
# print(sub_arr_cpy)

[0 1 2 3]


In [32]:
arr2d = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

# 전치 행렬
# print(arr2d.T)

# 항등행렬 np.eye
# eye는 눈이 아니라 identity matrix에서 유래됨
# identity: 자기 자신읠 유지하는 행렬 -> 곱해도 원래 행렬 유지함

import numpy as np
I = np.eye(3)
# print(I)

# reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshape_arr = arr.reshape(3, 3) # 숫자 안맞으면 에러남
print(reshape_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# 행렬에서 dot을 사용하면 한 행렬의 행 벡터와 다른 행렬의 열 벡터를 내적하여 새로운 행렬을 만들어요.
C = np.dot(A, B)
print(C)

[[ 58  64]
 [139 154]]


In [36]:
import numpy as np

random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.10650687 0.29113099 0.24081898]
 [0.92887367 0.77798983 0.34335864]
 [0.51991904 0.65221689 0.80990186]]


In [43]:
# 평균, 표준편차(Standard Deviation, σ)

import numpy as np

scores = [60, 70, 80, 90, 100]  # 점수 리스트
mean = np.mean(scores)
# print("mean: ", mean)

std = np.std(scores)
# print("std: ", std)

# ✅ 평균이 0, 표준편차가 1인 경우를 “표준 정규분포(Standard Normal Distribution)“라고 해요.
# ✅ 데이터가 0을 중심으로, ±1 범위 안에 68%가 있음

standardized = (scores - mean) / std
print(standardized)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
# 배열 기초 튜토리얼 (shape, dtype, size, ndim)

# 넘파이는 배열에 저장된 모든 요소가 같은 데이터 타입으로 맞춤
# 기본적으로 int32, float64같은 데이터 타입 씀
# dtype: check data type

arr2 = np.array([1, 2, 3, 4, 3.5])
# print(arr2.shape)
# print(arr2.dtype) # float64
# ✅ 모든 요소가 동일한 자료형이 되도록 자동 변환됨! (정수 1, 2, 3 → 실수 1.0, 2.0, 3.0)

# .size: returns the number of elements in array
arr4 = np.array([
      [1, 2, 3],
      [4, 5, 6],
    ])

# print(arr4.size) # 2 * 3 = 6

# .ndim: dimention of the array
arr5 = np.array([1, 2, 3])  # 1차원 배열
arr6 = np.array([[1, 2, 3], [4, 5, 6]])  # 2차원 배열
arr7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3차원 배열

# print(arr5.ndim)
# print(arr6.ndim)
# print(arr7.ndim)



(5,)
