<a href="https://colab.research.google.com/github/welovecherry/colab/blob/main/Numpy_study_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
# 넘파이는 한줄로 모든 요소에 10 더하기 가능

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_added = arr + 10
# print(arr_added)


# 넘파이는 자동 메모리 관리해줌.
# 씨언어는 2차원배열 만들 때 [3][3]처럼 크기를 명확히 해야하지만
# 넘파이는 이런걸 쓸 필요 없다.

matrix = np.array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix * 100)
print(matrix.T)
print(matrix) # original

# 넘파이: average, std(표준편차), sum 바로 사용가능
# print(np.mean(arr))
# print(np.std(arr))
# print(np.sum(arr))


[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 차원을 표현할 때 [] 를 쓴다. 만일 2차원 배열을 만들면 []를 2번 씀
# 2차원 배열 (행렬)
matrix = np.array([
    [1, 2, 3],    # 첫 번째 행
    [4, 5, 6],    # 두 번째 행
    [7, 8, 9]     # 세 번째 행
])
# 각 []는 차원을 나타냄
# 1번 []는 전체 행렬
# 2번 []는 각 행

# 3차원 배열 (텐서)
tensor = np.array([
    [[1, 2], [3, 4]],    # 첫 번째 2D 배열
    [[5, 6], [7, 8]]     # 두 번째 2D 배열
])
# 1번 []는 전체 텐서
# 2번 []는 각 2D 배열
# 3번 []는 각 2D 배열 내 행

In [59]:
matrix = np.array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# print(matrix[1, 2]) # 1행 2열 (idex starts from 0)

# 넘파이는 슬라이싱 사용 가능 (슬라이싱이 복사가 아니라 참조되므로 원본 배열이 변경될 수 있다.)
# print(matrix[:2])


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# print(arr[2:5])
# print(arr[:4])
# print(arr[5:])
# print(arr[:])

# print(arr[1:8:2])  # 인덱스 1부터 7까지 2칸씩 건너뛰기
# print(arr[::-1])   # 배열을 거꾸로 뒤집기
# print(arr[::3])    # 처음부터 끝까지 3칸씩 건너뛰기

# 2차원 배열에서도 넘파이 슬라이싱 사용 가능
arr2d = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

# 넘파이는 조건을 활용한 슬라이싱(필터링) 가능
# print(arr[arr > 4])


# (슬라이싱이 복사가 아니라 참조되므로 원본 배열이 변경될 수 있다.)
arr = np.array([1, 2, 3, 4])
sub_arr = arr[1:3]  # 부분 배열 (view)

sub_arr[0] = 99  # 부분 배열 수정
# print(arr)  # 원본 배열도 변경됨!


sub_arr_cpy = arr[1:3].copy()
sub_arr_cpy[0] = 10000
# print(arr)
# print(sub_arr_cpy)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
arr2d = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

# 전치 행렬
# print(arr2d.T)

# 항등행렬 np.eye
# eye는 눈이 아니라 identity matrix에서 유래됨
# identity: 자기 자신읠 유지하는 행렬 -> 곱해도 원래 행렬 유지함

import numpy as np
I = np.eye(10)
print(I)

# reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshape_arr = arr.reshape(3, 3) # 숫자 안맞으면 에러남
print(reshape_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# 행렬에서 dot을 사용하면 한 행렬의 행 벡터와 다른 행렬의 열 벡터를 내적하여 새로운 행렬을 만들어요.
C = np.dot(A, B)
print(C)

[[ 58  64]
 [139 154]]


In [36]:
import numpy as np

random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.10650687 0.29113099 0.24081898]
 [0.92887367 0.77798983 0.34335864]
 [0.51991904 0.65221689 0.80990186]]


In [62]:
# 평균, 표준편차(Standard Deviation, σ)

import numpy as np

scores = [60, 70, 80, 90, 100]  # 점수 리스트
mean = np.mean(scores)
# print("mean: ", mean)

std = np.std(scores)
# print("std: ", std)

# ✅ 평균이 0, 표준편차가 1인 경우를 “표준 정규분포(Standard Normal Distribution)“라고 해요.
# ✅ 데이터가 0을 중심으로, ±1 범위 안에 68%가 있음

standardized = (scores - mean) / std
print(standardized)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [8]:
import numpy as np
# 배열 기초 튜토리얼 (shape, dtype, size, ndim)

# 넘파이는 배열에 저장된 모든 요소가 같은 데이터 타입으로 맞춤
# 기본적으로 int32, float64같은 데이터 타입 씀
# dtype: check data type

arr2 = np.array([1, 2, 3, 4, 3.5 , 9])
# print(arr2.shape)
# print(arr2.dtype) # float64
# ✅ 모든 요소가 동일한 자료형이 되도록 자동 변환됨! (정수 1, 2, 3 → 실수 1.0, 2.0, 3.0)

# .size: returns the number of elements in array
arr4 = np.array([
      [1, 2, 3],
      [4, 5, 6],
    ])
# print(arr4.shape)
print(arr4.size) # 2 * 3 = 6

# .ndim: dimention of the array
arr5 = np.array([1, 2, 3])  # 1차원 배열
arr6 = np.array([[1, 2, 3], [4, 5, 6]])  # 2차원 배열
arr7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3차원 배열

print(arr5.ndim)
print(arr6.ndim)
print(arr7.ndim)



6
1
2
3


In [18]:
import numpy as np

arr1 = np.zeros(5)
# print(arr1)

arr2 = np.zeros((2, 3))
# print(arr2)

arr3 = np.zeros((3, 3), dtype=np.int32)
# print(arr3)

arr4 = np.ones(3)
# print(arr4)

arr5 = np.ones((3, 2))
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
'''
🔹 3. np.arange(): 범위 기반 배열 생성

✅ 연속된 숫자로 배열을 만들 때 사용
✅ Python의 range() 함수와 비슷하지만 배열을 반환
✅ start, stop, step 값을 지정 가능
'''
import numpy as np

arr1 = np.arange(10)
# print(arr1)

arr2 = np.arange(1, 10, 2) # before second element
# print(arr2)

arr3 = np.arange(5, 0, -1)
# print(arr3)


'''🔹 4. np.linspace(): “Linearly Spaced Numbers”**의 약자예요.
특정 구간을 일정한 간격으로 나눈 배열 생성

✅ 시작값과 끝값을 포함하여 일정한 간격으로 배열을 생성
✅ arange()와 다르게, 몇 개의 숫자를 만들지 직접 지정 가능
✅ num 파라미터로 요소 개수 설정 가능
'''

arr4 = np.linspace(0, 10, 5) # 0부터 10(포함)까지 5개로 나눔
# print(arr4)
arr5 = np.linspace(1, 5, 4) # 1부터 5까지(포함)해서 4개로 나눔
# print(arr5)

arr6 = np.linspace(0, 1, 6, endpoint=False) # 0부터 1까지 6개로 나누는데, 1은 포함 안함
# print(arr6)

# print(list(range(0, 5, 1)))
# print(list(range(0, 5, 0.1))) # error in python
arr7 = np.arange(1, 5, 0.5)
# print(arr7)

''' arange()를 언제 사용할까?

✅ 정수 범위 만들기 → range()와 유사하게 사용 가능
✅ 소수 간격으로 숫자 만들기
✅ NumPy 배열이 필요할 때 (ndarray로 생성됨)'''




[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# print(arr + 10)
# print(arr * 2)
# print(arr / 2) # result will be floating number
# print(arr ** 2) # square


''' 2. 배열 간 연산 (덧셈, 뺄셈, 곱셈, 나눗셈)

✅ 동일한 크기의 배열끼리는 요소별(Element-wise) 연산이 가능
✅ **+, -, *, /, //, %, ** 연산 모두 지원
'''

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# print(arr1 + arr2)
print(arr1 / arr2)
print(arr1 // arr2) # 몫 연산
print(arr2 % arr1) # modulo


print(5%2)

[0.25 0.4  0.5 ]
[0 0 0]
[0 1 0]
1


In [25]:
'''
🔹 3. 브로드캐스팅(Broadcasting) 개념

✅ 크기가 다른 배열끼리 연산할 때 자동으로 크기를 맞춰 연산하는 기능
✅ Python 리스트는 지원하지 않지만, NumPy에서는 자동 적용!
'''

''' ✅ (1) 배열과 스칼라 연산 → 자동 적용

배열과 숫자를 연산할 때, 숫자가 자동으로 모든 요소에 적용됨'''
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

# print(arr + 10)


''' ✅ (2) 1차원 vs 2차원 배열 연산

배열의 크기가 다르면, 자동으로 맞춰서 연산
: ✅ 1D 배열이 자동으로 2D 배열 크기로 맞춰짐! '''

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2 = np.array([10, 20, 30])
print(arr1 + arr2)

''' ✅ (3) 브로드캐스팅이 불가능한 경우

아래처럼 행 개수나 열 개수가 다르면 연산 불가능'''
arr3 = np.array([10, 20])
# print(arr1 + arr3) # results error: ValueError: operands could not be broadcast together with shapes (2,3) (2,)


[[11 22 33]
 [14 25 36]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [33]:
'''✅ (1) 배열 형태 변형 reshape()

✅ 배열의 차원과 모양을 변경할 때 사용
✅ 요소 개수는 변경 전과 후가 동일해야 함
✅ 차원을 변경해도 데이터는 그대로 유지됨!

📌 자동 크기 조정 (-1 사용)
'''
import numpy as np

arr = np.arange(12)
# reshaped = arr.reshape(3, 4)
# print(reshaped)

reshaped = arr.reshape(3, -1)
# arr.reshape(-1, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
